name: Release artifact

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Restore dependencies
        run: npm ci

      - name: Build Extension
        run: vsce package

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"